# Usando imagem oficial do Python
FROM python:3.12-slim

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos do projeto para dentro do container
COPY producer.py requirements.txt ./

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define comando padrão
CMD ["python", "producer.py"]
